

translate traditional_chinese strings:


    old "Acarhyn Citadel"
    new "阿卡海茵\"城堡\""
    old "Aegisthus Shipyards"
    new "埃癸斯託斯造船廠"
    old "Aegisthus"
    new "埃癸斯託斯"
    old "Agust"
    new "阿古斯特"
    old "Alf Cen"
    new "半人馬座α星"
    old "Alpha Centauri"
    new "半人馬座α星"
    old "Alpha Vulpeculae"
    new "狐狸座α星"
    old "Antoine"
    new "安託萬"
    old "Arderne"
    new "阿德恩"
    old "Ariah"
    new "阿瑞亞"
    old "Barranthular"
    new "巴蘭蘇拉"
    old "boverine"
    new "牛獾獸"
    old "boverin"
    new "牛獾獸"
    old "Calista"
    new "卡莉斯塔"
    old "calgound"
    new "獅狼獸"
    old "calgounds"
    new "獅狼獸"
    old "Cé"
    new "瑟"
    old "Cetruvar"
    new "塞特魯瓦"
    old "Citadel"
    new "\"城堡\""
    old "Cohort"
    new "\"羣體\""
    old "Council"
    new "議會"
    old "Council of Nkoy"
    new "倫科伊議會"
    old "Cucaniensis"
    new "庫卡尼恩西斯"
    old "Cyborg"
    new "賽博格"
    old "Double D's Casino"
    new "雙D賭場"
    old "Duncan"
    new "鄧肯"
    old "Elyot"
    new "埃利奧特"
    old "Enfield"
    new "\"恩菲爾德\"號"
    old "Garomph"
    new "加羅姆夫"
    old "Glixken"
    new "格裏克森"
    old "Grivans"
    new "格瑞萬斯"
    old "Heveliun Belt"
    new "赫維留天體帶"
    old "Hippolyta"
    new "希波呂忒"
    old "Holy Book"
    new "\"聖典\""
    old "Humans"
    new "人類"
    old "Hyborian"
    new "希波利安"
    old "Iana"
    new "伊安娜"
    old "Idaho"
    new "愛達荷"
    old "Jenne"
    new "珍妮"
    old "Karan"
    new "卡蘭"
    old "Hreir"
    new "瑞爾"
    old "SL-Drive"
    new "西拉斯-卡岑引擎"
    old "SL-drive"
    new "西拉斯-卡岑引擎"
    old "Katorr"
    new "卡託爾"
    old "Katorrian"
    new "卡託爾人"
    old "Keo"
    new "克歐"
    old "Kepler"
    new "開普勒星"
    old "Kualtha"
    new "庫爾薩"
    old "Kualtha juice"
    new "庫爾薩汁"
    old "Kualtha Juice"
    new "庫爾薩汁"
    old "Kyl"
    new "凱爾"
    old "Lanan"
    new "拉南星"
    old "Lyna"
    new "琳娜"
    old "Melody"
    new "梅洛迪"
    old "Melroot"
    new "魅魔草"
    old "Milord"
    new "大人"
    old "milord"
    new "大人"
    old "Moora"
    new "穆娜"
    old "Dr. Chrone Moora"
    new "克羅恩·穆娜醫生"
    old "Aunt Nadya"
    new "娜迪亞阿姨"
    old "Neon Swan"
    new "\"霓虹天鵝\""
    old "Nise"
    new "尼斯"
    old "Nyssa"
    new "妮莎"
    old "Paltrowians"
    new "帕爾特羅維安人"
    old "Pit of Despair"
    new "\"絕望之淵\""
    old "Premier"
    new "\"首領\""
    old "priest caste"
    new "祭司團"
    old "warrior caste"
    new "戰士團"
    old "Head Priestess"
    new "女大祭司"
    old "head priestess"
    new "女大祭司"
    old "Proxima Centauri Orbital"
    new "比鄰星軌道站"
    old "Queen"
    new "女王"
    old "Rae"
    new "蕾"
    old "Raisha"
    new "蕾莎"
    old "Ranimo"
    new "拉尼莫"
    old "R'o tribe"
    new "拉歐人部落"
    old "Ryūjin"
    new "龍神"
    old "Shuty Station"
    new "夏提空間站"
    old "Sill"
    new "西爾"
    old "Sovereignty"
    new "\"至高權域\""
    old "Szuzume"
    new "蘇珠美"
    old "Tartarus"
    new "塔爾塔羅斯"
    old "Tavort"
    new "塔沃特"
    old "Kyl Tavort"
    new "凱爾·塔沃特"
    old "Terran"
    new "人族"
    old "TGN"
    new "人族星系艦隊"
    old "Academy"
    new "學院"
    old "Terran Galactic Naval Academy"
    new "人族星系艦隊學院"
    old "Navy"
    new "艦隊"
    old "Jaculus"
    new "\"翼蛇\"號"
    old "Ypotryll"
    new "\"異龍\"號"
    old "Bastard"
    new "\"私生子\"號"
    old "The Mysteries"
    new "\"神祕會\""
    old "Skandersfelt"
    new "斯坎德斯菲爾特"
    old "Tiberius"
    new "提比略"
    old "Trellka"
    new "崔爾卡"
    old "Twi』ll"
    new "特維爾人"
    old "Tyber"
    new "泰伯"
    old "Typhon"
    new "泰豐星"
    old "Valenmann"
    new "瓦倫曼"
    old "Valenmann de Lonval"
    new "瓦倫曼·德·隆瓦爾"
    old "Valenmann de Lonval family"
    new "瓦倫曼·德·隆瓦爾家族"
    old "Vbrecl"
    new "韋布瑞克人"
    old "Verdant"
    new "\"翠綠\""
    old "Verdigris"
    new "銅綠星"
    old "Verdigris V"
    new "銅綠星5號星"
    old "Vicious Souls Alliance"
    new "\"惡魂聯盟\""
    old "Vitriv"
    new "維特裏夫"
    old "Von"
    new "馮"
    old "Vulpes"
    new "迅狐星"
    old "Kyl Zaghav"
    new "凱爾·扎加夫"
    old "Confessor"
    new "\"懺悔者\""
    old "Virgine Queen"
    new "\"處女之王\""
    old "captain"
    new "艦長"
    old "Captain"
    new "艦長"
    old "moon"
    new "衛星"
    old "Psi1 Draconis"
    new "天龍座ψ1號星"
    old "Psi1 Draconis system"
    new "天龍座ψ1號星系"
    old "Fifth Glorious Campaign"
    new "\"第五次榮耀之戰\""
    old "galaxy"
    new "星系"
    old "Kyldjar"
    new "凱爾賈爾"
    old "Naval Academy"
    new "艦隊學院"
    old "ship"
    new "飛船"
    old "workshop"
    new "工場"
    old "Hero of the Acarhyn"
    new "\"阿卡海茵英雄\""
    old "Rivas"
    new "瑞瓦斯"
    old "Velaine"
    new "維萊恩"
    old "Asret Tangle"
    new "阿斯瑞特之藤"
    old "Trallragh"
    new "崔爾拉族"
    old "His Holiness"
    new "\"聖座\""
    old "codritium"
    new "科德裏姆礦"

    old "Mistress"
    new "女主人"


    old "cyborg"
    new "賽博格"

    old "Bodyguard"
    new "貼身守衛"

    old "LOCATION"
    new "地點"

    old "Previous Entry"
    new "上個條目"

    old "Next Entry"
    new "下個條目"

    old "Close Entry"
    new "關閉條目"

    old "Girl"
    new "女孩"

    old "Guard"
    new "守衛"

    old "Robot"
    new "機器人"

    old "Woman"
    new "女人"

    old "R'o Chieftain"
    new "拉歐人首領"

    old "R'o Woman"
    new "拉歐女人"

    old "R'o Guard"
    new "拉歐守衛"

    old "R'o Virgin"
    new "拉歐處女"

    old "Thug"
    new "流氓"

    old "Bot"
    new "機器人"

    old "Man"
    new "男人"

    old "Warrior"
    new "戰士"

    old "Receptionist"
    new "接待員"

    old "Translator"
    new "翻譯員"

    old "Mechanic"
    new "機修工"

    old "Slave"
    new "奴隸"

    old "Doctor"
    new "醫生"

    old "Merc"
    new "僱傭兵"

    old "Prisoner"
    new "囚犯"

    old "Mech"
    new "機甲"

    old "Commander"
    new "指揮官"

    old "Priestess"
    new "女祭司"

    old "Crowd"
    new "人羣"

    old "Admiral"
    new "艦隊上將"

    old "Board Member"
    new "董事會成員"

    old "Dr. Rivas"
    new "瑞瓦斯博士"

    old "Chairwoman"
    new "女主席"

    old "Quartermaster"
    new "軍需官"

    old "Hunter"
    new "獵手"

    old "Acarhyn Priest"
    new "阿卡海茵祭司"

    old "Announcer"
    new "廣播員"

    old "Official"
    new "官員"

    old "Manager"
    new "經紀人"

    old "Mercenary"
    new "僱傭兵"

    old "Noral"
    new "諾拉"
# Decompiled by unrpyc: https://github.com/CensoredUsername/unrpyc
